/**
 * Plan Builder
 *
 * Converts a planner-produced SolutionConfig into an ordered list of
 * individual MCP tool calls against tools that actually exist and work
 * today: AEP (schema/dataset/segment), CJA (data view/segment/calculated
 * metric), AJO (journey/offer/activation), and RAG (knowledge search for
 * grounding/context).
 *
 * This deliberately does NOT call msb_execute_solution / orchestrator_*.
 * Those require infra identifiers the planner cannot produce (client_name,
 * site_repo, netlify_site_id) and are bound by a 30s Lambda timeout that a
 * 9-phase build cannot complete within. See PR discussion for details.
 *
 * Each step declares the MCP tool name + a template for its arguments.
 * Arguments may reference outputs of earlier steps via the `refs` field —
 * the runner resolves these at execution time once dependent steps finish.
 */

import { SolutionConfig } from './types';

export interface PlannedStep {
  id: string;
  label: string;
  tool: string;
  category: 'rag' | 'aep' | 'cja' | 'ajo';
  critical: boolean;
  /** Static arguments known ahead of time. */
  args: Record<string, any>;
  /**
   * Dynamic argument refs: maps an arg name to `${stepId}.${resultPath}`.
   * Resolved once the referenced step has completed successfully.
   */
  refs?: Record<string, string>;
}

function slug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 40) || 'item';
}

/**
 * Build the ordered step plan for a given SolutionConfig.
 *
 * Order rationale:
 *  1. RAG grounding — search knowledge base for the vertical (context only,
 *     non-critical, never blocks later steps).
 *  2. AEP foundation — one XDM schema, one dataset built on it, then one
 *     segment per planner-identified segment (schema/dataset are
 *     prerequisites for meaningful segmentation).
 *  3. CJA analytics — resolve a data view, then create one segment mirror
 *     and one calculated metric for reporting on the same audience.
 *  4. AJO activation — one journey per planner-identified segment (entry
 *     criteria referencing the AEP segment created in step 2), then
 *     activate each journey.
 */
export function buildStepPlan(config: SolutionConfig): PlannedStep[] {
  const steps: PlannedStep[] = [];
  const vertical = config.business_vertical || 'general';
  const domain = config.website_domain || 'example.com';
  const segments = Array.isArray(config.segments) ? config.segments : [];
  const destinations = Array.isArray(config.destinations) ? config.destinations : [];

  // ── 1. RAG grounding (non-critical — informational only) ─────────────────
  steps.push({
    id: 'rag_adobe',
    label: `Search Adobe knowledge base for "${vertical}" patterns`,
    tool: 'search_adobe_knowledge',
    category: 'rag',
    critical: false,
    args: { query: `${vertical} segmentation and personalization best practices` },
  });

  // ── 2. AEP foundation ──────────────────────────────────────────────────────
  const schemaStepId = 'aep_schema';
  steps.push({
    id: schemaStepId,
    label: `Create XDM profile schema for ${domain}`,
    tool: 'adobe_create_schema',
    category: 'aep',
    critical: true,
    args: {
      title: `${slug(domain)}_${vertical}_profile`,
      base_class: 'https://ns.adobe.com/xdm/context/profile',
      description: `Profile schema for ${domain} (${vertical}) generated by harness build`,
    },
  });

  const datasetStepId = 'aep_dataset';
  steps.push({
    id: datasetStepId,
    label: `Create dataset backed by the new schema`,
    tool: 'adobe_create_dataset',
    category: 'aep',
    critical: true,
    args: {
      name: `${slug(domain)}_${vertical}_dataset`,
      description: `Dataset for ${domain} profile data`,
    },
    refs: { schema_ref_id: `${schemaStepId}.$id` },
  });

  const segmentStepIds: string[] = [];
  const segmentList = segments.length > 0
    ? segments
    : [{ name: 'engaged_visitors', pql_expression: "profile.visits > 1", description: 'Default segment — planner returned none' }];

  segmentList.forEach((seg: any, idx: number) => {
    const stepId = `aep_segment_${idx}`;
    segmentStepIds.push(stepId);
    steps.push({
      id: stepId,
      label: `Create AEP segment: ${seg.name || `segment_${idx}`}`,
      tool: 'adobe_create_segment',
      category: 'aep',
      critical: false,
      args: {
        name: seg.name || `segment_${idx}`,
        pql_expression: seg.pql_expression || "profile.visits > 1",
        description: seg.description || '',
      },
    });
  });

  // ── 3. CJA analytics ───────────────────────────────────────────────────────
  const dataViewStepId = 'cja_data_views';
  steps.push({
    id: dataViewStepId,
    label: 'Resolve an available CJA data view',
    tool: 'cja_list_data_views',
    category: 'cja',
    critical: false,
    args: { limit: 5 },
  });

  const cjaSegmentStepId = 'cja_segment';
  steps.push({
    id: cjaSegmentStepId,
    label: `Mirror primary segment in CJA for reporting`,
    tool: 'cja_create_segment',
    category: 'cja',
    critical: false,
    args: {
      name: `${segmentList[0]?.name || 'engaged_visitors'}_cja`,
      description: `CJA reporting segment mirroring AEP segment for ${vertical}`,
      definition: {
        func: 'segment',
        version: [1, 0, 0],
        container: {
          func: 'container',
          context: 'sessions',
          pred: {
            func: 'event',
            evt: { func: 'metric', name: 'metrics/pageviews' },
            op: 'gt',
            val: 1,
          },
        },
      },
    },
    refs: { data_view_id: `${dataViewStepId}.data_views.0.id` },
  });

  const cjaMetricStepId = 'cja_metric';
  steps.push({
    id: cjaMetricStepId,
    label: `Create calculated metric for ${vertical} engagement`,
    tool: 'cja_create_calculated_metric',
    category: 'cja',
    critical: false,
    args: {
      name: `${vertical}_engagement_rate`,
      description: `Engagement rate metric for ${domain}`,
      metric_type: 'DECIMAL',
      polarity: 'positive',
      definition: {
        func: 'calc-metric',
        version: [1, 0, 0],
        formula: {
          func: 'metric',
          name: 'metrics/pageviews',
        },
      },
    },
    refs: { data_view_id: `${dataViewStepId}.data_views.0.id` },
  });

  // ── 4. AJO activation (only if an activation-style destination exists) ────
  const wantsActivation = destinations.length === 0 || destinations.some((d: string) =>
    ['email', 'web', 'push', 'sms'].includes(String(d).toLowerCase())
  );

  if (wantsActivation) {
    segmentList.forEach((seg: any, idx: number) => {
      const journeyStepId = `ajo_journey_${idx}`;
      steps.push({
        id: journeyStepId,
        label: `Create AJO journey for ${seg.name || `segment_${idx}`}`,
        tool: 'msb_create_ajo_journey',
        category: 'ajo',
        critical: false,
        args: {
          name: `${vertical}_${seg.name || `segment_${idx}`}_journey`,
          entry_criteria: { type: 'segment', segment_name: seg.name || `segment_${idx}` },
        },
      });

      steps.push({
        id: `ajo_activate_${idx}`,
        label: `Activate journey for ${seg.name || `segment_${idx}`}`,
        tool: 'msb_activate_ajo_campaign',
        category: 'ajo',
        critical: false,
        args: {},
        refs: { journey_id: `${journeyStepId}.journey_id` },
      });
    });
  }

  return steps;
}

/**
 * Resolve a dotted path like "aep_schema.$id" or "cja_data_views.data_views.0.id"
 * against a map of stepId -> result payload.
 */
export function resolveRef(ref: string, results: Record<string, any>): any {
  const [stepId, ...pathParts] = ref.split('.');
  let value: any = results[stepId];
  for (const part of pathParts) {
    if (value === undefined || value === null) return undefined;
    const idx = Number(part);
    value = Number.isInteger(idx) && !Number.isNaN(idx) && Array.isArray(value)
      ? value[idx]
      : value[part];
  }
  return value;
}
