/**
 * AgentStep — one model turn per invocation. This is the inversion at the
 * heart of the Step Functions loop: the ?sync=1 runAgent() runs
 * generateText() in a `stopWhen: stepCountIs(maxSteps)` loop with tools
 * that execute themselves; here each turn is exactly one Step Functions
 * state, tools are stubs (lib/llm/tool-catalog.ts's buildToolStubs — no
 * execute function, so generateText stops after emitting the calls instead
 * of running them), and Step Functions' RouteStep Choice state owns the
 * iteration. Actual execution happens afterwards in the exec-tools Lambda.
 */

import { generateText, stepCountIs, type ModelMessage } from 'ai';
import { resolveModel } from '@/lib/llm/model-registry';
import { buildToolStubs } from '@/lib/llm/tool-catalog';
import { systemPrompt, stage } from '@/lib/llm/agent-core';
import { loadRun, checkpointStep } from '@/lib/execution-store';
import type { PendingToolCall } from '@/lib/types';
import { asModelProviderError, asStateStoreError } from '../_shared/errors';
import type { LoopEnvelope } from '../_shared/envelope';

export const handler = async (env: LoopEnvelope): Promise<LoopEnvelope> => {
  const run = await asStateStoreError(() => stage('state store (loadRun)', () => loadRun(env.runId)));

  const result = await asModelProviderError(() =>
    stage(`chat model call (${run.model})`, () =>
      generateText({
        model: resolveModel(run.model),
        system: systemPrompt(run.allowFullBuild),
        messages: run.messages as ModelMessage[],
        tools: buildToolStubs(run.selectedTools),
        stopWhen: stepCountIs(1),
      })
    )
  );

  // Verified against the installed `ai` package version (7.0.16): the
  // messages generated by this call live on result.responseMessages, NOT
  // result.response.messages — in this version result.response is the
  // deprecated LanguageModelResponseMetadata shape and has no .messages.
  // Persisted verbatim so it round-trips into the next call's `messages`
  // unchanged.
  const newMessages: ModelMessage[] = result.responseMessages;
  const toolCalls: PendingToolCall[] = result.toolCalls.map((tc) => ({
    toolCallId: tc.toolCallId,
    toolName: tc.toolName,
    input: tc.input,
  }));

  const stepCount = env.stepCount + 1;

  if (toolCalls.length === 0) {
    await asStateStoreError(() =>
      checkpointStep(env.runId, { newMessages, pendingToolCalls: null, status: 'COMPLETED', stepCountDelta: 1 })
    );
    return { ...env, stepCount, status: 'DONE' };
  }

  if (stepCount >= env.maxSteps) {
    await asStateStoreError(() =>
      checkpointStep(env.runId, { newMessages, pendingToolCalls: toolCalls, status: 'MAX_STEPS', stepCountDelta: 1 })
    );
    return { ...env, stepCount, status: 'MAX_STEPS' };
  }

  await asStateStoreError(() =>
    checkpointStep(env.runId, {
      newMessages,
      pendingToolCalls: toolCalls,
      status: 'RUNNING',
      stepCountDelta: 1,
    })
  );

  return { ...env, stepCount, status: 'TOOL_CALLS' };
};
